FROM scratch

LABEL description="To be used as a volume to store Cypres test artifacts"

WORKDIR /artifacts

# Assuming build context is cypress directory
COPY screenshots screenshots
COPY videos videos