#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#
#students:
#    path: /student/
#    controller: App\Controller\DefaultController::index
studentsjson:
  path: students.json
  controller: App\Controller\StudentsJSONController::index